
// .res entries:
models/cc_head.mdl
models/nm_ccskin.mdl
models/bathroom_toilet.mdl
sound/nm_hq_lemonjustice.wav
sound/nm_hq_choppa.wav
sound/nm_hq_311stayhome.wav
sound/nm_hq_gcratshit.wav
sound/nm_hq_gcscream2.wav
sound/nm_hq_lbholy.wav
sound/nm_hq_gcscream1.wav
sound/nm_hq_foldsdog.wav
sound/nm_hq_gcpassing.wav
sound/nm_hq_gcasshole1.wav
sound/nm_hq_yaketysax.wav
sound/nm_hq_gcscab2.wav
sound/nm_hq_gcscab1.wav
sound/nm_hq_elobluesky.wav
sound/nm_hq_gcasshole2.wav
sound/nm_hq_gcasshole3.wav
sound/nm_hq_dchahayou.wav
sound/nm_hq_dchorseattack.wav
sound/nm_hq_dctorture.wav
sound/nm_hq_dchatesteam.wav
sprites/glow01.spr
sprites/nm_blue.spr
sprites/nm_green.spr
sprites/nm_red.spr
sprites/nm_white.spr
sprites/nm_yellow.spr
